### ISSUE TITLE
This section should use a pointer instead of a default cursor

### ISSUE THREAD

**Issue by JhohannesK** [mkaatman/tirecomparecalc#2]
![image](https://github.com/mkaatman/tirecomparecalc/assets/75913666/cf28f2d5-b50e-471f-9255-7ddd8504b424)

Having the cursor being a pointer will tell users the sections is clickable (UX)

**Comment by mkaatman** [comment]
Good point. Fixed. https://github.com/mkaatman/tirecomparecalc/commit/f70630195cc7e730f5f330030c2dc06ed539e1a0

Should redeploy shortly.
